### ISSUE TITLE
Add yml-based config files

### ISSUE THREAD

**Issue by behdad** [googlei18n/fontmake#4]
It's painful to pass many arguments on the command-line.  We should have a way to pass a yml file, similar to fontbakery:

  https://github.com/googlefonts/fontbakery

We probably should have sections for sources (.glyphs, UFO, .fea, mti, ...), outputs to generate, and for each output (or globally), options like "remove overlap", "optimize", "fix outline directions", "autohint", etc.

In some distant future, this will become pluggable plugins / modules, and the optimizations in pyftsubset, as well as fixes that @dcrossland needs ala fontbakery, they all become part of fontmake configurable pipeline.

In some even more distant future, we'll configure pipelines using a data-flow graph...

**Comment by davelab6** [comment]
Love it!

**Comment by MrBrezina** [comment]
Reminds me a little bit of what we are trying to do with our tool MrHandy (not online yet) and what I suggested @davelab6 a while back. Here is a snippet to give you an idea. `$` calls a shell command once for the whole workflow, commands (e.g. in `init, cleanup, compile`) are references to Python modules, `$$` for each style while replacing `%f` with source path (defined in from). This is using AFDKO, but works equally well with fontmake. Then you just call it `mrhandy -g init` or `mrhandy -g init,compile` etc.

```yaml
  name: Nassim
  from:
    folder: .
    family: Nassim
    # the &styles anchor is used here, so the list of styles can be referenced later
    styles: &styles [Regular, Italic, Medium, MediumItalic, Semibold, SemiboldItalic, Bold, BoldItalic, Extrabold, ExtraboldItalic]
    formats: [ufo, ttf]
    AFDKOFolders: true
  to:
    folder: ../../fonts/Nassim/
    family: Nassim
    # reference to styles specified above
    styles: *styles
    formats: [otf, ttf]
  cleanup:
    - mrhandy.fdk.cleanup
  init:
    - $ makeInstancesUFO -d Nassim-Uprights.designspace -a -c -n
    - $ makeInstancesUFO -d Nassim-Italics.designspace -a -c -n
    - $$ checkOutlinesUFO -e -all %f:
        formats: [ufo]
    - $$ autohint -q %f:
        formats: [ufo]
    - mrhandy.fdk.fkern:
        formats: [ufo]
    - mrhandy.fdk.mark:
        formats: [ufo]
        useExtension: true
  compile:
    - mrhandy.fdk.makeotf
    - mrhandy.post.ttfautohint:
        formats: [ttf]
    - mrhandy.post.addDSIG
```
